apiVersion: v1
kind: ServiceAccount
metadata:
  name: ingress-admin
  namespace: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingress-admin
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["networking.k8s.io"] # "" indicates the core API group
  resources: ["ingresses"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: ingress-admin
subjects:
- kind: ServiceAccount
  name: ingress-admin
  namespace: dev
roleRef:
  kind: ClusterRole
  name: ingress-admin
  apiGroup: rbac.authorization.k8s.io