#eksctl create iamidentitymapping \
#  --cluster eks-hrm-dev \
#  --arn arn:aws:iam::473555546883:user/JENKINS \
#  --username JENKINS
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deploy
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["*"]
- apiGroups: ["extensions","apps"]
  resources: ["deployments"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jenkins-deploy
subjects:
- kind: User
  name: JENKINS
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: deploy
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-read-only
rules:
- apiGroups:
  - ""
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
  - create
- apiGroups:
  - extensions
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-read-binding
subjects:
- kind: User
  name: dev-read
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: dev-read-only
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-deploy
subjects:
- kind: User
  name: dev-read
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: deploy
  apiGroup: rbac.authorization.k8s.io

